apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: "{{ DEPLOY_APP }}"
  namespace: teamcrm
  labels:
    team: teamcrm
spec:
  image: "{{ image }}"
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /isAlive
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 30
  prometheus:
    enabled: true
    path: /metrics
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 10m
      memory: 512Mi
  accessPolicy:
    outbound:
      external:
        - host: login.salesforce.com
        - host: navdialog.my.salesforce.com
  envFrom:
    - secret: sf-pdl-kafka
  kafka:
    pool: nav-prod # enum of nav-dev, nav-prod
  env:
    - name: CONTEXT
      value: PROD
    - name: POSTER_SETTINGS # DEFAULT, FROM_BEGINNING, NO_POST, SAMPLE, RUN_ONCE, ENCODE_KEY, AVRO_KEY_VALUE, AVRO_VALUE
      value: SAMPLE, FROM_BEGINNING, NO_POST, RUN_ONCE
    - name: KAFKA_POLL_DURATION
      value: '10000'
    - name: KAFKA_CLIENTID
      value: sf-pdl-kafka
    - name: KAFKA_TOPIC_PERSONDOKUMENT
      value: pdl.pdl-persondokument-v1
    - name: KAFKA_TOPIC_GEOGRAFISKTILKNYTNING
      value: pdl.geografisktilknytning-v1
    - name: MS_BETWEEN_WORK
      value: '240000'
    - name: SF_TOKENHOST
      value: https://login.salesforce.com
    - name: DEPLOY_APP
      value: "{{ DEPLOY_APP }}"
    - name: WHITELIST_FILE
      value: '/whitelist/prod.json'